# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_version = "20240821.0.1"

  config.vm.network "forwarded_port", guest: 80, host: 8888, host_ip: "127.0.0.1"

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.synced_folder "C:/vagrant-project/sources/11-training-php", "/var/www/html"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    # Lệnh này sẽ dừng kịch bản ngay lập tức nếu có lỗi
    set -e
    # Lệnh này ngăn các cửa sổ hỏi đáp khi cài đặt
    export DEBIAN_FRONTEND=noninteractive

    # Cập nhật hệ thống
    apt-get update -y

    # Thêm kho PPA cho PHP
    apt-get install -y software-properties-common
    add-apt-repository ppa:ondrej/php -y
    apt-get update -y

    # Cài đặt Apache và PHP
    apt-get install -y apache2 php8.1 libapache2-mod-php8.1 php8.1-mysql php8.1-mbstring php8.1-xml php8.1-curl
    
    # Cấu hình Apache
    a2enmod rewrite
    sed -i '/<Directory \/var\/www\/html>/,/<\/Directory>/ s/AllowOverride None/AllowOverride All/' /etc/apache2/sites-available/000-default.conf
    
    # Gán quyền sở hữu thư mục web cho Apache
    chown -R www-data:www-data /var/www/html

    # Khởi động lại Apache để áp dụng tất cả thay đổi
    systemctl restart apache2
  SHELL
  
  config.vm.boot_timeout = 600 
end
